### PR TITLE
Popovermenus redsandro persist

### PR DESCRIPTION
**Pull request by Redsandro**
I was thinking something simple like this. Ideally (but only necessary in the event of an expansion/update) the function would merge the `localStorage` contents with (new) defaults if-not-exists, but I've spend most of the time I've allotted to this patch trying to build portainer, and I have to go to work now.

### CODE REVIEW

**Comment by 1138-4EB** [comment]
Seems I messed it up... You were working in the branch before I cleaned it. Anyway, I will cherry pick your commits, and rebase them on top of portainer/portainer#1412.

**Comment by Redsandro** [comment]
@1138-4EB I tried to merge in from upstream but I broke it.. I hope you can do it without too much trouble.

**Comment by Redsandro** [comment]
@1138-4EB here is the original commit before I broke it trying to merge in upstream:

https://github.com/Redsandro/portainer/commit/2f8f356fd9b0776980d49a624b9b0c918f957b64

**Comment by 1138-4EB** [comment]
I am finishing a merge right now. I'll pick it asap.

**Comment by Redsandro** [comment]
You're fast. :+1:

**Comment by Redsandro** [comment]
@1138-4EB Any chance you could do `git commit --amend --author="Redsandro <redsandro@gmail.com>"`?

I accidentally did this on my work computer using my full name and (ironically) anonymous account.

**Comment by Redsandro** [comment]
@1138-4EB Thanks so much. :+1: This was a small educational moment for me.

**Comment by 1138-4EB** [comment]
@Redsandro thank you too. It was for both :D. I'm not used to having contributions to my own branches and I abuse history rewrites. This was definitely a lesson.

**Pull request closed without merging**
